### ISSUE TITLE
Broken Link in next.rsuitejs.com

### ISSUE THREAD

**Issue by praisethemoon** [rsuite/rsuite.github.io#122]
Hello, In CheckerPicker component as well as Popup component, the `container and prevent overflow` sections refers to broken link which is 
```
/**
 *  PreventOverflowContainer from
 *  https://github.com/rsuite/rsuite.github.io/blob/master/src/components/PreventOverflowContainer.js
 */
```

any idea if this can be fixed? I really need that `PreventOverflowContainer`, thanks!

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite.github.io/blob/next/src/components/PreventOverflowContainer.js

**Comment by praisethemoon** [comment]
You are awesome :D thanks! Feel free to close the issue now or after updating the docs! 🎉

**Comment by simonguo** [comment]
In the near future, when the next branch is merged into the master branch, these links will be accessible.
